### ISSUE TITLE
Exercise 01

### ISSUE THREAD

**Issue by amadden80** [emilylordahl/testtest#1]
completenes: 3
comfort: -5

Comment:  this was so great... so great

https://github.com/amadden80/testtest/blob/master/w01/d01/submissiont.js

**Comment by emilylordahl** [comment]
That is interesting....    do it rgith?

**Comment by amadden80** [comment]
Oh now it makes so much send

**Comment by emilylordahl** [comment]
Great

**Comment by emilylordahl** [comment]
try using better varible names
```js
var banana;
```

Get it?

**Comment by amadden80** [comment]
oh yeah!  haha   good point
```js
var bananananana;
```
